"""
models.py
─────────────────────────────────────────────────────────────────────────────
All SQLAlchemy ORM models for ReviewSnipper — one file, no subfolders.

Models in this file:
    User              — registered platform user accounts
    ProcessedWebhook  — idempotency log for Stripe webhook events

Models to be added here in later stages:
    Business           — Stage 3
    Competitor         — Stage 3
    PlatformConnection — Stage 3
    RawReview          — Stage 4
    AnalysisSnapshot   — Stage 5
─────────────────────────────────────────────────────────────────────────────
"""

from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import UUID

from .database import Base


# ═════════════════════════════════════════════════════════════════════════════
# USER
# ═════════════════════════════════════════════════════════════════════════════

class User(Base):
    """
    A registered ReviewSnipper user account.

    Tracks identity, authentication credentials, the user's primary brand
    profile (name + global lat/long coordinates), subscription status,
    and trial period.

    Subscription status values:
        free_tier  — permanent free plan (default on registration)
        trial      — 14-day Pro trial (auto-started on registration)
        starter    — £29/month paid plan
        smb_pro    — £79/month paid plan
        agency     — £149/month paid plan (coming soon)
        cancelled  — cancelled, access ends at period end

    Location fields use latitude/longitude (not postcodes) so the product
    works globally — UK, US, Canada, Australia — with zero code changes.
    """

    __tablename__ = "users"

    # ── Primary key ───────────────────────────────────────────────────────────
    # UUID generated by PostgreSQL — never by Python — preventing collisions
    # when multiple registrations arrive at the same instant.
    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        nullable=False,
        comment="Unique user identifier — generated by PostgreSQL",
    )

    # ── Identity ──────────────────────────────────────────────────────────────
    # Unique index for fast login lookups.
    # Always stored in lowercase — enforced in /auth/register and /auth/login.
    email = Column(
        String(320),
        unique=True,
        nullable=False,
        index=True,
        comment="User email address — stored lowercase, unique per account",
    )

    # ── Authentication ────────────────────────────────────────────────────────
    # bcrypt hash — the plaintext password is NEVER stored anywhere.
    hashed_password = Column(
        String(72),
        nullable=False,
        comment="bcrypt hash of the user password — never store plaintext",
    )

    # ── Brand profile ─────────────────────────────────────────────────────────
    # Set during onboarding after registration — all three fields are nullable
    # because they are not required at sign-up time.
    target_brand_name = Column(
        String(255),
        nullable=True,
        comment="Name of the user's primary tracked business",
    )

    # Latitude of the primary business — e.g. 51.5074 (London), 40.7128 (NYC)
    target_brand_lat = Column(
        Float,
        nullable=True,
        comment="Latitude coordinate for global competitor radius search",
    )

    # Longitude of the primary business — e.g. -0.1278 (London), -74.0060 (NYC)
    target_brand_long = Column(
        Float,
        nullable=True,
        comment="Longitude coordinate for global competitor radius search",
    )

    # ── Subscription ──────────────────────────────────────────────────────────
    # Updated by Stripe webhook events handled in /api/v1/billing/webhook.
    subscription_status = Column(
        String(32),
        nullable=False,
        default="free_tier",
        server_default="free_tier",
        comment="Current plan — updated by Stripe webhooks",
    )

    # NULL for permanent free_tier users.
    # Set on registration for trial users; cleared when a paid plan starts.
    trial_ends_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Trial expiry — NULL if no trial active",
    )

    # Set the first time a user starts a paid subscription via Stripe Checkout.
    stripe_customer_id = Column(
        String(64),
        nullable=True,
        unique=True,
        comment="Stripe customer ID — NULL until first paid subscription",
    )

    # Set to True when the user clicks the link in their welcome email.
    is_verified = Column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
        comment="True once the user verifies their email address",
    )

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
        comment="UTC timestamp when the account was created",
    )

    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
        onupdate=datetime.now(timezone.utc),
        comment="UTC timestamp of the last account update",
    )

    def __repr__(self) -> str:
        return (
            f"<User id={self.id} email={self.email} "
            f"subscription={self.subscription_status}>"
        )


# ═════════════════════════════════════════════════════════════════════════════
# PROCESSED WEBHOOK
# ═════════════════════════════════════════════════════════════════════════════

class ProcessedWebhook(Base):
    """
    Idempotency log for Stripe webhook events.

    Every webhook event received is recorded here BEFORE any user data
    is changed. If the same event ID arrives a second time (Stripe retries
    on timeout), we detect the duplicate and return 200 immediately without
    modifying anything.

    Why the Stripe event ID is the primary key:
        Stripe event IDs are globally unique strings like "evt_1OqXyZ...".
        Using them as the primary key means a duplicate INSERT is rejected
        at the database level (IntegrityError), providing a second safety
        layer beyond our application-level duplicate check.

    Status values:
        processed — event handled successfully, user data updated
        failed    — event handling failed, transaction rolled back
    """

    __tablename__ = "processed_webhooks"

    # Stripe event ID — e.g. "evt_1OqXyZ2eZvKYlo2CXmFrQ8Rp"
    # Used as primary key — no separate unique index needed.
    id = Column(
        String(128),
        primary_key=True,
        nullable=False,
        comment="Stripe event ID — primary key for idempotency",
    )

    # The Stripe event type — stored for audit trail and debugging.
    # Example values: "checkout.session.completed",
    #                 "customer.subscription.updated"
    event_type = Column(
        String(128),
        nullable=True,
        comment="Stripe event type string",
    )

    # Processing outcome.
    status = Column(
        String(32),
        nullable=False,
        comment="processed | failed",
    )

    # Error summary — populated only when status = 'failed'.
    # Capped at 500 characters to prevent runaway storage.
    error_detail = Column(
        Text,
        nullable=True,
        comment="Error summary if processing failed — for debugging",
    )

    # UTC timestamp of when the event was received.
    processed_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
        comment="UTC timestamp when the event was processed",
    )

    def __repr__(self) -> str:
        return (
            f"<ProcessedWebhook id={self.id} "
            f"type={self.event_type} status={self.status}>"
        )